[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
streamlana = "CQapQthxRSpDEEoj1EQ2S9Esj4uZxPSwC49pKufQfo3z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/biboux/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
